export const SUBSCRIPTION_PLANS_CHANGE = "SUBSCRIPTION_PLANS_CHANGE";
export const PAYMENT_PROVIDERS_CHANGE = "PAYMENT_PROVIDERS_CHANGE";
export const PAYMENT_MODAL_TOGGLE = "PAYMENT_MODAL_TOGGLE";
export const PAYMENT_SUCCESS_MODAL_TOGGLE = "PAYMENT_SUCCESS_MODAL_TOGGLE";
export const PROMOTION_CAMPAIGN_CHANGE = "PROMOTION_CAMPAIGN_CHANGE";
export const PAYMENT_ICONS_CHANGE = "PAYMENT_ICONS_CHANGE";
