export const LIVE_CLASSES_CHANGE = "LIVE_CLASSES_CHANGE";
export const UPDATE_LIVE_CLASS = "UPDATE_LIVE_CLASS";
export const REMOVE_LIVE_CLASS = "REMOVE_LIVE_CLASS";
export const LIVE_CLASS_NOTIFY_TOGGLE = "LIVE_CLASS_NOTIFY_TOGGLE";
