export const COURSES_CHANGE = "COURSES_CHANGE";
export const ENROLLED_COURSES_CHANGE = "ENROLLED_COURSES_CHANGE";
export const COURSE_UPDATE = "COURSE_UPDATE";
export const SET_SELECTED_COURSE = "SET_SELECTED_COURSE";
export const SELECTED_COURSE_UPDATE = "SELECTED_COURSE_UPDATE";
export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_QUIZ = "SET_QUIZ";
export const SET_QUIZ_SOLUTION = "SET_QUIZ_SOLUTION";
export const SET_QUIZ_SUMMARY = "SET_QUIZ_SUMMARY";
