export const COURSES_CHANGE = "COURSES_CHANGE";
export const ENROLLED_COURSES_CHANGE = "ENROLLED_COURSES_CHANGE";
export const COURSE_UPDATE = "COURSE_UPDATE";
export const SELECTED_COURSE_UPDATE = "SELECTED_COURSE_UPDATE";
