export const SET_SCHEDULE = "SET_SCHEDULE";
export const SCHEDULE_CHANGE = "SCHEDULE_CHANGE";
export const SET_WEEKLY_PROGRESS = "SET_WEEKLY_PROGRESS";
export const REPEAT_WEEKLY_SCHEDULE_CHANGE = "REPEAT_WEEKLY_SCHEDULE_CHANGE";

export const REMOVE_SCHEDULE_ITEM = "REMOVE_SCHEDULE_ITEM";
export const UPDATE_SCHEDULE_ITEM = "UPDATE_SCHEDULE_ITEM";
